[window]
dimensions = { columns = 100, lines = 30 }

[font]
size = 14.0

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

# -----------------------------------------------------------------------------
# Ayu Theme from https://github.com/alacritty/alacritty-theme
# -----------------------------------------------------------------------------

[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'
